apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentv2
  namespace: webapp
  labels:
    app: employees
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v2
  template:
    metadata:
      labels:
        app: employees
        version: v2
    spec:
      containers:
      - name: employee-rohanv2
        image: 487784775349.dkr.ecr.us-east-1.amazonaws.com/clo835_rohan_repository_webapp:v2.0
        ports:
        - containerPort: 8080
        env: 
        - name: DBHOST
          value: "sql-service.sqldb.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "pass123"
        - name: APP_COLOR
          value: "lime"  
        - name: DATABASE
          value: "employees"
          


          
          