apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rohan-replica
  namespace: webapp
  labels:
      app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: employee-myapp
        image: 487784775349.dkr.ecr.us-east-1.amazonaws.com/clo835_rohan_repository_webapp:v1.0
        ports:
        - containerPort: 8080
        env: 
        - name: DBHOST
          value: "sql-service.sqldb.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "pass123"
        - name: APP_COLOR
          value: "pink"  
        - name: DATABASE
          value: "employees"
          
