apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
  template:
    metadata:
  spec:
      containers:
      - name: employee-webapp
        image: 487784775349.dkr.ecr.us-east-1.amazonaws.com/clo835_rohan_repository_webapp:v1.0
        ports:
        - containerPort: 8080
        env: 
        - name: DBHOST
          value: "mysql-service.sqldb.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "pass123"
        - name: APP_COLOR
          value: "pink"  
        - name: DATABASE
          value: "employees"
          


          
          