apiVersion: v1
kind: Pod
metadata:
  name: rohan-webapp
spec:
  containers:
  - name: employee-webapp
    image: 487784775349.dkr.ecr.us-east-1.amazonaws.com/clo835_rohan_repository_webapp:v1.0
    ports:
    - containerPort: 8080
    env: 
    - name: DBHOST
      value: "" #sql ip address
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: "root"
    - name: DBPWD
      value: "pass123"
    - name: APP_COLOR
      value: "blue"  
    - name: DATABASE
      value: "employees"
  